// Mirrors the `customers` table in supabase/migrations/0001_init_schema.sql.
// Kept deliberately narrow for the seeded demo dataset — the DB columns themselves are
// free text (see docs/DATABASE.md), but everything this project generates uses these values.

export type ConsultationStatus = "completed" | "no_show" | "scheduled";
export type PurchaseStatus = "purchased" | "not_purchased";

/** A customer as generated by the seed script, before a `clinic_id` is attached. */
export interface SeedCustomer {
  name: string;
  email: string | null;
  phone: string | null;
  treatment: string;
  provider: string;
  consultation_status: ConsultationStatus;
  purchase_status: PurchaseStatus;
  amount_spent: number;
  /** ISO date, `YYYY-MM-DD`. */
  last_visit: string;
  rebooked: boolean;
  satisfaction_score: number;
  notes: string | null;
}

/** A persisted customer row. */
export interface Customer extends SeedCustomer {
  id: string;
  clinic_id: string;
  created_at: string;
}
